.travis.yml
CHANGELOG.rst
README.rst
docs/conf.py
requirements/base.txt
requirements/dev.txt
requirements/doc.in
requirements/doc.txt
requirements/quality.txt
requirements/test.txt
tox.ini
user_tasks/__init__.py

* Switch the docs to use edx-sphinx-theme
* Fix the Travis conditions for uploading a PyPI release
* More badges on the README, and don't let them vanish on PyPI (which strips the title line)
* Upgrade assorted dependencies (and ignore one of the 2 mutually exclusive new pydocstyle warnings about starting a multi-line comment)

PLAT-1083 Use edx-sphinx-theme for docs

---

docs/conf.py
requirements/dev.txt
requirements/doc.txt
requirements/travis.txt
tox.ini

Builds were failing on Read the Docs because it doesn't set `DJANGO_SETTINGS_MODULE` like tox does.  Now doing this directly in `docs/conf.py` instead.
Also upgraded dependencies again via pip-compile; no major changes.

Fix Read the Docs builds

---

.travis.yml
CHANGELOG.rst
docs/conf.py
docs/getting_started.rst
docs/internationalization.rst
requirements/base.in
requirements/base.txt
requirements/dev.in
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.txt
requirements/travis.in
requirements/travis.txt
setup.py
tests/test_signals.py
tox.ini
user_tasks/__init__.py
user_tasks/apps.py
user_tasks/conf.py
user_tasks/rules.py
user_tasks/tasks.py

Added some code and documentation to help prevent race conditions due to delays in committing the status record for new tasks.  I ran afoul of this when testing a view with atomic requests enabled.  The subsequent Travis run ran afoul of the setuptools upgrade, so I also did a bit of cleanup:
* Updated testing dependency versions
* Fixed minor issues reported by the newer pylint version
* Switched Python 3 testing from 3.5 to 3.6
* Fixed a minor formatting issue with the changelog section titles

Better handling of delayed transaction commits

---

.travis.yml
Makefile
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt
requirements/test.txt
requirements/travis.txt

Two of the requirements files were out of order in the `make upgrade` target, fix them so it works again.  Also, stop running a duplicate set of tests on branch pushes and make it easier to display verbose output from `pip-compile`.

Fix the make upgrade file order

---

user_tasks/admin.py

In the admin config, search_fields specified to search task statuses on user, which is a ForeignKey. Instead, we now search on user__username and user__email.

Fix search in UserTaskStatusAdmin

---

CHANGELOG.rst
user_tasks/__init__.py
user_tasks/signals.py

Meant to address https://openedx.atlassian.net/browse/EDUCATOR-4597

Close old/obsolete connections in start_user_task handler.

---

CHANGELOG.rst
tests/test_signals.py
user_tasks/__init__.py
user_tasks/signals.py

* Fixes broken devstack course-publishing process.

check transaction atomicity before forcing closed any django DB connections

---

.travis.yml

The last version bump didn't go out automatically because this environment variable name changed in the rest of the file.  Already used the Jenkins job to do the deployment, so just fixing this for future updates.

Fix PyPI deployment condition

---

Makefile
requirements/base.txt
requirements/celery44.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/test.txt
requirements/travis.txt

Adding pin importlib-metadata==1.7.0 to avoid error in make upgrade.
Upgrade celery version in base.txt
NOTE:  **In followup PR i will remove the extra celery workers testings from tox.**

Adding pin importlib-metadata==1.7.0 and upgrade celery 

---

requirements/base.txt
requirements/celery40.txt
requirements/celery43.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/test.txt
requirements/travis.txt

- `importlib-metadata` was constrained because `importlib-metadata==2.0.0` was causing conflicts in running `make upgrade` with `python3.5` due to conflicts in `tox` and `virtualenv` requirements.
- Unpinned `importlib-metadata` constraint after fixing the issue in https://github.com/pypa/virtualenv/pull/1953 and https://github.com/tox-dev/tox/pull/1682.

Unpin importlib-metadata constraint

---

.travis.yml
requirements/celery31.txt
requirements/celery40.txt
requirements/celery42.txt
requirements/celery43.txt
tox.ini

Removing un-necessary celery versions testing.
4.4.7 already deployed in all repos so its safe to remove these test vers.

Removing un-necessary celery versions testing.

---

CHANGELOG.rst
user_tasks/__init__.py
user_tasks/tasks.py

Module celery.task will be removed in 5.0 but since new import is compatible with 4.4.7 so updating the code.
https://docs.celeryproject.org/en/v4.4.7/internals/deprecation.html#removals-for-version-5-0
This is 2nd PR https://github.com/edx/django-user-tasks/pull/104 where add the tox for testing.

Module celery.task will be removed in 5.0

---

.github/workflows/ci.yml
CHANGELOG.rst
Makefile
requirements/base.txt
requirements/celery44.txt
requirements/celery50.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt
tests/test_admin.py
tests/test_models.py
tests/test_rest_api.py
tests/test_serializers.py
tests/test_signals.py
tests/test_tasks.py
tox.ini
user_tasks/__init__.py
user_tasks/signals.py

Part1: https://github.com/edx/django-user-tasks/pull/106
This is Part2
https://openedx.atlassian.net/browse/BOM-2165
- Adding celery50 testing.
- `from celery.task import Task` is removed in celery5.0. Updated the `import` since its working in `4.4.7` also. Made some changes in code  [Documentation](https://docs.celeryproject.org/en/v4.4.7/internals/deprecation.html#removals-for-version-5-0)
- make upgrade using py3.8

Adding celery50 testing and update import for Task

---

CHANGELOG.rst
user_tasks/__init__.py

Bump the version 2.0.1.
Releasing https://github.com/edx/django-user-tasks/pull/104
and https://github.com/edx/django-user-tasks/pull/106
and few others changes.
I have added constraint in edx-platform. After testing on sandbox remove that constraint.
```
greater version requires testing. Will remove this constraint after testing.
django-user-tasks==1.3.2
```

feat: Bump the version and releasing new changes.

---

.github/workflows/ci.yml

chore: disabling the fail_ci_if_error temporarily.
https://github.com/codecov/codecov-action/issues/330

chore: disabling the fail_ci_if_error temporarily.

---

.github/workflows/ci.yml
CHANGELOG.rst
Makefile
requirements/base.txt
requirements/celery50.txt
requirements/celery52.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/test.txt
tox.ini
user_tasks/__init__.py

This PR removes Celery<5 pin from requirements, so resolves a dependency conflict in https://github.com/openedx/edx-platform/pull/29046.
For more information, please see the linked PR.

feat!: bump celery and drop python 3.5

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt
schema/settings.py
schema/urls.py

This PR was created on behalf of [PR](https://github.com/openedx/django-user-tasks/pull/176) to solve some conflicts regarding python 3.8 dependencies.

Replace swagger to drf_yasg

---

README.rst

We're moving to a single standard set of guidelines across the whole
openedx organization.

docs: Update the link to the contributing guidelines.

---

CHANGELOG.rst
docs/conf.py
requirements/doc.in
requirements/doc.txt

The edx-sphinx theme is being deprecated, and replaced with sphinx-book-theme. This removes references to the deprecated theme and replaces them with the new standard theme for the platform.
**Testing instructions:** 
- Run `make docs` and see that the docs are generated properly and use the sphinx-book-theme

chore: Switch from edx-sphinx-theme to sphinx-book-theme.

---

.github/workflows/ci.yml
CHANGELOG.rst
Makefile
requirements/base.txt
requirements/celery44.txt
requirements/celery52.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/quality.txt
requirements/test.txt
schema/urls.py
setup.py
tox.ini
user_tasks/__init__.py
user_tasks/admin.py

Issue: https://github.com/edx/upgrades/issues/134
Upgrade to Django 4.2
Django42 will work with `drf==3.14.0`. We are using only compatible versions for tests.
Removed celery other versions since `edx-platform` is already using latest celery version.

feat: Upgrade to Django 4.2

---

.readthedocs.yml
requirements/ci.in
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/quality.txt

- Removed `tox-battery` requirement as it is not needed with `tox>4` anymore.

fix: remove tox-battery requirement

---

docs/conf.py
docs/readme.rst
requirements/base.txt
requirements/ci.txt
requirements/constraints.txt
requirements/dev.txt
requirements/doc.in
requirements/doc.txt
requirements/quality.txt
requirements/test.txt

Related to https://github.com/openedx/django-user-tasks/issues/316 & https://github.com/openedx/django-user-tasks/issues/291

Ditch swagger2rst dependency

---

.github/workflows/ci.yml
requirements/base.txt
requirements/ci.in
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip.txt

Update codecov to the latest version and start using the org-wide token for uploads.
See https://github.com/openedx/wg-frontend/issues/179

build: Update codecov and use token

---

user_tasks/models.py

Per OEP-30 these annotations should live with their models. I'm just moving them from the edx-platform safelist to their correct home.

docs: Add PII annotations

---

docs/internationalization.rst

Convert links from edx.readthedocs.io to links on docs.openedx.org

docs: Update edx.rtd.io links to docs.openedx.org
